package com.dejavu.backend.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * ROOM BLUEPRINT ENTITY
 * 
 * Order in gameplay: Phase 2 (Server Generation)
 * This class represents a single instance of a haunted room generated by the AI (or fallback).
 * It holds the selected background, the hidden confession, the poetic clues, and the objects.
 * This entity is stored in the database so that a user's session can reference it.
 */
@Entity
@Table(name = "room_blueprints")
public class RoomBlueprint {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private Long confessionId;
    
    private String language;
    
    private String roomTitle;
    private String detectedPlace;
    private String primaryEmotion;
    
    @Column(columnDefinition = "TEXT")
    private String themesJson;
    
    @Transient
    @JsonProperty("themes")
    private List<String> themesList;
    
    private String backgroundAssetId;
    
    @Column(columnDefinition = "TEXT")
    private String objectAssetIdsJson;
    
    @Transient
    @JsonProperty("objectAssetIds")
    private List<String> objectAssetIdsList;
    
    @Column(columnDefinition = "TEXT")
    private String openingAngelLine;
    
    @Column(columnDefinition = "TEXT")
    private String clue1;
    
    @Column(columnDefinition = "TEXT")
    private String clue2;
    
    @Column(columnDefinition = "TEXT")
    private String extraClue3;
    
    @Column(columnDefinition = "TEXT")
    private String extraClue4;
    
    @Column(columnDefinition = "TEXT")
    private String customScoringParams;
    
    @Column(columnDefinition = "TEXT")
    private String hiddenTargetSummary;
    
    @Column(columnDefinition = "TEXT")
    private String winAngelLine;
    
    @Column(columnDefinition = "TEXT")
    private String translatedConfession;
    
    private boolean generatedByModel;
    
    private LocalDateTime createdAt;

    /**
     * Entity lifecycle callback.
     * Automatically sets the creation timestamp before inserting into the database.
     */
    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public Long getConfessionId() { return confessionId; }
    public void setConfessionId(Long confessionId) { this.confessionId = confessionId; }

    public String getLanguage() { return language; }
    public void setLanguage(String language) { this.language = language; }

    public String getRoomTitle() { return roomTitle; }
    public void setRoomTitle(String roomTitle) { this.roomTitle = roomTitle; }

    public String getDetectedPlace() { return detectedPlace; }
    public void setDetectedPlace(String detectedPlace) { this.detectedPlace = detectedPlace; }

    public String getPrimaryEmotion() { return primaryEmotion; }
    public void setPrimaryEmotion(String primaryEmotion) { this.primaryEmotion = primaryEmotion; }

    public String getThemesJson() { return themesJson; }
    public void setThemesJson(String themesJson) { this.themesJson = themesJson; }

    /**
     * Special Jackson setter for AI JSON mapping.
     * Takes a list of themes from the AI and converts it into a JSON string for database storage.
     */
    @JsonProperty("themes")
    public void setThemesList(List<String> themesList) {
        this.themesList = themesList;
        try {
            this.themesJson = new ObjectMapper().writeValueAsString(themesList);
        } catch (Exception e) {}
    }

    public String getBackgroundAssetId() { return backgroundAssetId; }
    public void setBackgroundAssetId(String backgroundAssetId) { this.backgroundAssetId = backgroundAssetId; }

    public String getObjectAssetIdsJson() { return objectAssetIdsJson; }
    public void setObjectAssetIdsJson(String objectAssetIdsJson) { this.objectAssetIdsJson = objectAssetIdsJson; }

    /**
     * Special Jackson setter for AI JSON mapping.
     * Takes the array of object IDs from the AI and converts it into a JSON string for database storage.
     */
    @JsonProperty("objectAssetIds")
    public void setObjectAssetIdsList(List<String> objectAssetIdsList) {
        this.objectAssetIdsList = objectAssetIdsList;
        try {
            this.objectAssetIdsJson = new ObjectMapper().writeValueAsString(objectAssetIdsList);
        } catch (Exception e) {}
    }

    public String getOpeningAngelLine() { return openingAngelLine; }
    public void setOpeningAngelLine(String openingAngelLine) { this.openingAngelLine = openingAngelLine; }

    public String getClue1() { return clue1; }
    public void setClue1(String clue1) { this.clue1 = clue1; }

    public String getClue2() { return clue2; }
    public void setClue2(String clue2) { this.clue2 = clue2; }

    public String getExtraClue3() { return extraClue3; }
    public void setExtraClue3(String extraClue3) { this.extraClue3 = extraClue3; }

    public String getExtraClue4() { return extraClue4; }
    public void setExtraClue4(String extraClue4) { this.extraClue4 = extraClue4; }

    public String getCustomScoringParams() { return customScoringParams; }
    public void setCustomScoringParams(String customScoringParams) { this.customScoringParams = customScoringParams; }

    public String getHiddenTargetSummary() { return hiddenTargetSummary; }
    public void setHiddenTargetSummary(String hiddenTargetSummary) { this.hiddenTargetSummary = hiddenTargetSummary; }

    public String getWinAngelLine() { return winAngelLine; }
    public void setWinAngelLine(String winAngelLine) { this.winAngelLine = winAngelLine; }

    public String getTranslatedConfession() { return translatedConfession; }
    public void setTranslatedConfession(String translatedConfession) { this.translatedConfession = translatedConfession; }

    public boolean isGeneratedByModel() { return generatedByModel; }
    public void setGeneratedByModel(boolean generatedByModel) { this.generatedByModel = generatedByModel; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
